package aws

//go:generate go run ../../cmd/aws-generator aws_gen.go

import (
	"github.com/schidstorm/wg-ondemand/pkg/provision"
)

var locations = []provision.Location{
	{
		Latitude:  -33.9253,
		Longitude: 18.4239,
		Country:   "Africa",
		City:      "Cape Town",
		Key:       "af-south-1",
	},
	{
		Latitude:  22.3,
		Longitude: 114.2,
		Country:   "Asia Pacific",
		City:      "Hong Kong",
		Key:       "ap-east-1",
	},
	{
		Latitude:  35.6897,
		Longitude: 139.6922,
		Country:   "Asia Pacific",
		City:      "Tokyo",
		Key:       "ap-northeast-1",
	},
	{
		Latitude:  37.56,
		Longitude: 126.99,
		Country:   "Asia Pacific",
		City:      "Seoul",
		Key:       "ap-northeast-2",
	},
	{
		Latitude:  34.6939,
		Longitude: 135.5022,
		Country:   "Asia Pacific",
		City:      "Osaka",
		Key:       "ap-northeast-3",
	},
	{
		Latitude:  19.0761,
		Longitude: 72.8775,
		Country:   "Asia Pacific",
		City:      "Mumbai",
		Key:       "ap-south-1",
	},
	{
		Latitude:  17.3617,
		Longitude: 78.4747,
		Country:   "Asia Pacific",
		City:      "Hyderabad",
		Key:       "ap-south-2",
	},
	{
		Latitude:  1.3,
		Longitude: 103.8,
		Country:   "Asia Pacific",
		City:      "Singapore",
		Key:       "ap-southeast-1",
	},
	{
		Latitude:  -33.8678,
		Longitude: 151.21,
		Country:   "Asia Pacific",
		City:      "Sydney",
		Key:       "ap-southeast-2",
	},
	{
		Latitude:  -6.175,
		Longitude: 106.8275,
		Country:   "Asia Pacific",
		City:      "Jakarta",
		Key:       "ap-southeast-3",
	},
	{
		Latitude:  -37.8142,
		Longitude: 144.9631,
		Country:   "Asia Pacific",
		City:      "Melbourne",
		Key:       "ap-southeast-4",
	},
	{
		Latitude:  3.1478,
		Longitude: 101.6953,
		Country:   "Asia Pacific",
		City:      "Malaysia",
		Key:       "ap-southeast-5",
	},
	{
		Latitude:  30.5593,
		Longitude: -91.0369,
		Country:   "Canada",
		City:      "Central",
		Key:       "ca-central-1",
	},
	{
		Latitude:  51.05,
		Longitude: -114.0667,
		Country:   "Canada West",
		City:      "Calgary",
		Key:       "ca-west-1",
	},
	{
		Latitude:  50.1106,
		Longitude: 8.6822,
		Country:   "Europe",
		City:      "Frankfurt",
		Key:       "eu-central-1",
	},
	{
		Latitude:  47.3744,
		Longitude: 8.5411,
		Country:   "Europe",
		City:      "Zurich",
		Key:       "eu-central-2",
	},
	{
		Latitude:  59.3294,
		Longitude: 18.0686,
		Country:   "Europe",
		City:      "Stockholm",
		Key:       "eu-north-1",
	},
	{
		Latitude:  45.4669,
		Longitude: 9.19,
		Country:   "Europe",
		City:      "Milan",
		Key:       "eu-south-1",
	},
	{
		Latitude:  40.4169,
		Longitude: -3.7033,
		Country:   "Europe",
		City:      "Spain",
		Key:       "eu-south-2",
	},
	{
		Latitude:  53.35,
		Longitude: -6.2603,
		Country:   "Europe",
		City:      "Ireland",
		Key:       "eu-west-1",
	},
	{
		Latitude:  51.5072,
		Longitude: -0.1275,
		Country:   "Europe",
		City:      "London",
		Key:       "eu-west-2",
	},
	{
		Latitude:  48.8567,
		Longitude: 2.3522,
		Country:   "Europe",
		City:      "Paris",
		Key:       "eu-west-3",
	},
	{
		Latitude:  0,
		Longitude: 0,
		Country:   "Israel",
		City:      "Tel Aviv",
		Key:       "il-central-1",
	},
	{
		Latitude:  0,
		Longitude: 0,
		Country:   "Middle East",
		City:      "UAE",
		Key:       "me-central-1",
	},
	{
		Latitude:  26.225,
		Longitude: 50.5775,
		Country:   "Middle East",
		City:      "Bahrain",
		Key:       "me-south-1",
	},
	{
		Latitude:  -23.55,
		Longitude: -46.6333,
		Country:   "South America",
		City:      "Sao Paulo",
		Key:       "sa-east-1",
	},
	{
		Latitude:  0,
		Longitude: 0,
		Country:   "US East",
		City:      "N. Virginia",
		Key:       "us-east-1",
	},
	{
		Latitude:  0,
		Longitude: 0,
		Country:   "US East",
		City:      "Ohio",
		Key:       "us-east-2",
	},
	{
		Latitude:  0,
		Longitude: 0,
		Country:   "US West",
		City:      "N. California",
		Key:       "us-west-1",
	},
	{
		Latitude:  41.6524,
		Longitude: -83.4321,
		Country:   "US West",
		City:      "Oregon",
		Key:       "us-west-2",
	},
}
